### ISSUE TITLE
Oddities with weapon learning

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#124] opened 2021-01-21 12:23 UTC
It seems that a pawn with the corresponding knowledge about some weapon cannot prioritize training that weapon if there is any other weapon present around about which this pawn has no corresponding knowledge.

There is a newly created "Crashlanded" scenario with [Greatbow] tech researched via DevMode.
There is a [Target Stand] with active bill [Learn to shoot a weapon] with all the weapons enabled by default.
There is a default [Bolt-action rifle] and some spawned via DevMode [Greatbow]s scattered around.
There is a pawn that wants to learn to shoot a greatbow, but is unable to.

But! Once I forbid that lying-on-the-ground [Bolt-action rifle] or exclude it in the bill details, the pawn becomes available to prioritize training.

_In this picture, **only two** weapons are allowed in the bill details: **Greatbow** and **Bolt-action rifle**:_
![screenshot31](https://user-images.githubusercontent.com/62316596/105349271-84a09480-5bfa-11eb-8a70-ac62c6aef3ed.png)

There is another oddity in this behavior: If I spawn another Bolt-action rifle and left it _allowed_, there is still a possibility to train a greatbow, while the **default** rifle is still _forbidden_.

**Comment by jptrrs** [comment] 2021-01-22 04:42
Thanks for taking the time to test it out and reproduce. I found the cause of this behaviour - it was a consequence from the way RimWorld searches for ingredients when performing a recipe job. It should be fixed on the incoming update. Thanks!

**Closed as completed by jptrrs** 2021-01-22 04:42 UTC
Labels: bug
