### ISSUE TITLE
CtD when a pawn inteacts with research (havy modded

### ISSUE THREAD

**Issue by Kupferdrache** [jptrrs/HumanResources#41] opened 2020-06-20 18:50 UTC
Any inaction with the benchs caus a CtD, new install, all workshop versions, new map, one day in I set up the first two benches to get going with getting some books and start building some basic accomodations for the crashlanded crew.

No gamelog get created, while crashing.

Log: https://gist.github.com/d88c5eaf865b3e8958c15eaad22e7672
[CtD-save.zip](https://github.com/jptrrs/HumanResources/files/4808414/CtD-save.zip)

**Comment by jptrrs** [comment] 2020-06-21 01:59
Thanks for the file and the log, Kupferdrache. 
I've tried running your file, but without the mods you use its impossible for me to pinpoint the issue. I can tell you were trying to document a technology, but that's it. 
Can you please try this to isolate the problem?

1. Reset your mod list to only Harmony, the Core, HugsLib and Research Tree/Pal followed by this mod, and restart.
2. Turn on the developer tools on options and click on that quickstart button at the top of your screen to generate a new game quickly (pick the smallest map for speed).
3. Try to reproduce what you were doing when the error happened. Use the god mode if you have to build stuff and the debug actions menu if you need to. If its an error on load, you can save this game and try reloading it to test it out. If it doesn't happen, then it's something else. In that case:
4. Back on the mod list, try adding any other mod you were using. Add one by one, restarting and repeating the last step until you cause that error again. Yes, it might take a while if you're using too many mods... but you can also add a bunch at a time and, when that error pops up, you'll be able to refine your search to those last mods you added. I recommend RimPy to deal with large mod lists easily.

Thanks.

**Comment by jptrrs** [comment] 2020-07-25 12:24
Closing due to lack of answer.

**Closed as completed by jptrrs** 2020-07-25 12:24 UTC
Labels: needs more info
