### ISSUE TITLE
Error when trying to learn to shoot a weapon

### ISSUE THREAD

**Issue by Reiquard** [jptrrs/HumanResources#130] opened 2021-02-03 22:44 UTC
Initial data:
 - Just-started and paused "Lost tribe" scenario (with someone that has knowledge of the **[Recurve bow]**),
 - God-mode-installed **[Target Stand]** with **"Learn to shoot a weapon"** bill _(all weapons are allowed)_
 - **"Study"** set to **high priority (1)** for the pawn we have to test (the one who _doesn't know_ how to shoot a recurve bow yet)
 - **[Recurve bow]** spawned via Dev-Mode

Redraft this pawn (it goes to the bow to start shooting the target stand);
Redraft it immediately again and here's an error popped up:

```
HumanResources.WorkGiver_LearnWeapon provided target Thing_Target24564 but yielded no actual job for pawn Ибис. The CanGiveJob and JobOnX methods may not be synchronized.
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
RimWorld.JobGiver_Work:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_PrioritySorter:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Tagger:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Subtree:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Conditional:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.ThinkNode_Priority:TryIssueJobPackage(Pawn, JobIssueParams)
Verse.AI.Pawn_JobTracker:DetermineNextJob(ThinkTreeDef&)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob()
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean, Boolean)
RimWorld.Pawn_DraftController:set_Drafted(Boolean)
RimWorld.Pawn_DraftController:<GetGizmos>b__13_1()
Verse.Command_Toggle:ProcessInput(Event)
Verse.GizmoGridDrawer:DrawGizmoGrid(IEnumerable`1, Single, Gizmo&)
RimWorld.InspectGizmoGrid:DrawInspectGizmoGridFor(IEnumerable`1, Gizmo&)
RimWorld.MainTabWindow_Inspect:DrawInspectGizmos()
RimWorld.InspectPaneUtility:ExtraOnGUI(IInspectPane)
RimWorld.MainTabWindow_Inspect:ExtraOnGUI()
Verse.WindowStack:WindowStackOnGUI()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:Verse.Root.OnGUI_Patch1(Root)
```
https://gist.github.com/HugsLibRecordKeeper/7aeb9f5e69fe9aaf3423e8fd8b56e4db

**_An addition:_**

If the pawn is equipped with a **[Short bow]** at the moment of trying to learn to shoot a **[Recurve bow]**, there will be another error:

```
Verse.Pawn_EquipmentTracker container tried to drop  Bow_Recurve24565 which it didn't contain.
Verse.Log:Error(String, Boolean)
Verse.ThingOwner:TryDrop_NewTmp(Thing, IntVec3, Map, ThingPlaceMode, Thing&, Action`2, Predicate`1, Boolean)
Verse.ThingOwner`1:TryDrop(Thing, IntVec3, Map, ThingPlaceMode, ThingWithComps&, Action`2, Predicate`1)
Verse.Pawn_EquipmentTracker:TryDropEquipment(ThingWithComps, ThingWithComps&, IntVec3, Boolean)
HumanResources.JobDriver_LearnWeapon:<MakeNewToils>b__16_2()
Verse.AI.JobDriver:Cleanup(JobCondition)
Verse.AI.Pawn_JobTracker:CleanupCurrentJob(JobCondition, Boolean, Boolean, Boolean)
Verse.AI.Pawn_JobTracker:EndCurrentJob(JobCondition, Boolean, Boolean)
RimWorld.Pawn_DraftController:set_Drafted(Boolean)
RimWorld.Pawn_DraftController:<GetGizmos>b__13_1()
Verse.Command_Toggle:ProcessInput(Event)
Verse.GizmoGridDrawer:DrawGizmoGrid(IEnumerable`1, Single, Gizmo&)
RimWorld.InspectGizmoGrid:DrawInspectGizmoGridFor(IEnumerable`1, Gizmo&)
RimWorld.MainTabWindow_Inspect:DrawInspectGizmos()
RimWorld.InspectPaneUtility:ExtraOnGUI(IInspectPane)
RimWorld.MainTabWindow_Inspect:ExtraOnGUI()
Verse.WindowStack:WindowStackOnGUI()
RimWorld.UIRoot_Play:UIRootOnGUI()
Verse.Root:Verse.Root.OnGUI_Patch1(Root)
```
Note that the pawn is trying to drop **Bow_Recurve24565**, even though it is equipped with a **[Short bow]**

Another output_log with this error and _"full startup report"_ turned on, if it will help:
https://gist.github.com/HugsLibRecordKeeper/76728d6b63733e1321fb842b8cf7f73c

**Comment by Reiquard** [comment] 2021-02-06 00:01
I was able to eliminate the second error by editing [this condition](https://github.com/jptrrs/HumanResources/blob/f5b5c08585935b18d1ceefe9340e3e0ea9452a6f/Source/Work/JobDriver_LearnWeapon.cs#L223):

`                if (pawn.equipment.Primary != null && !practice)
`

changed to

`                if (pawn.equipment.Primary == (ThingWithComps)job.targetB.Thing && !practice)
`

**Comment by Reiquard** [comment] 2021-02-06 01:18
And now for the main issue.
There is a [condition](https://github.com/jptrrs/HumanResources/blob/f5b5c08585935b18d1ceefe9340e3e0ea9452a6f/Source/Work/WorkGiver_LearnWeapon.cs#L101) under the "**StartBillJob**" method:

`            if (Find.TickManager.TicksGame >= bill.lastIngredientSearchFailTicks + range.RandomInRange)
`

**bill.lastIngredientSearchFailTicks** initially equals to **-99999**
and after the first pass of this method, its value is set to **0**
**range.RandomInRange** gives a random number in the range **500-600**
So if at the moment of the second pass of this method _(after the pawn was redrafted)_, **Find.TickManager.TicksGame** was less than **500-600** _(the game is paused)_**_*_**, the method returns a **null** job, which seems to be the reason for this error:

`HumanResources.WorkGiver_LearnWeapon provided target Thing_Target24564 but yielded no actual job for pawn Pawn
`

**_*_** It was also possible to get this error much later, when **Find.TickManager.TicksGame** was over 600:
[bill.lastIngredientSearchFailTicks = Find.TickManager.TicksGame](https://github.com/jptrrs/HumanResources/blob/f5b5c08585935b18d1ceefe9340e3e0ea9452a6f/Source/Work/WorkGiver_LearnWeapon.cs#L148)


I tried to change the above condition to see what will happen:
`if (Find.TickManager.TicksGame >= bill.lastIngredientSearchFailTicks)
`
And the error has gone away.

_I have no confidence that changing this condition will not cause something bad to happen, so I leave it all up to you to decide what to do about it._

**Comment by Reiquard** [comment] 2021-02-06 22:46
Another way to prevent this error, and therefore the inability to perform other pawn tasks, is to make the following changes to the "[HasJobOnThing](https://github.com/jptrrs/HumanResources/blob/f5b5c08585935b18d1ceefe9340e3e0ea9452a6f/Source/Work/WorkGiver_LearnWeapon.cs#L39)" method, like I wrote it [here](https://github.com/jptrrs/HumanResources/issues/107#issuecomment-774549272):
`return ValidateChosenWeapons(bill, pawn, t as IBillGiver);`
change to
`return base.HasJobOnThing(pawn, t) && ValidateChosenWeapons(bill, pawn, t as IBillGiver);`

After that, although the pawn in the situation we created is no longer prevented from performing other tasks with a lower priority, it will not try to start practicing itself until the player right-clicks on the **[Target Stand]**
```
if (FloatMenuMakerMap.makingFor == pawn)
  bill.lastIngredientSearchFailTicks = 0;
```

By the way, I think #107 should be reopened.

**Comment by jptrrs** [comment] 2021-02-07 00:12
Actually, I already restructured the whole JobOnThing processes. Currently testing. Check this branch: https://github.com/jptrrs/HumanResources/tree/HiTechResearch

**Comment by Reiquard** [comment] 2021-02-07 02:16
Installed HumanResources-HiTechResearch.
After repeating all the steps described [here](https://github.com/jptrrs/HumanResources/issues/130#issue-800760833), have received a spamming errors.
https://gist.github.com/HugsLibRecordKeeper/69e1fd88d8f51f4452b4aebb6925954a

P.S. Tested it both with the old save and by creating the new game.
P.P.S Built [Book Shelf] doesn't allow to document tech, but if it's destroyed/not built, documentation is allowed.

**Comment by jptrrs** [comment] 2021-02-07 02:38
Well, like I said, still testing. No surprises there, nothing is guaranteed here before this branch is merged into the master and properly tagged as a version.
The documenting issue I literally just fixed! 
That error is weird as it manifests on ColonistBarColonistDrawer, a method we don't even touch! It looks more like something was missing from the file you loaded. We would need the log from the new game to look for an error.

**Comment by Reiquard** [comment] 2021-02-07 11:23
Well, it's the same with the updated mod and newly created scenario:
https://gist.github.com/5e08952c9f8dc68f0d102d20f7affa2f

**_Initial error in the log:_**

````
System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.AI.Job.MakeDriver (Verse.Pawn driverPawn) [0x00000] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.AI.Pawn_JobTracker.StartJob (Verse.AI.Job newJob, Verse.AI.JobCondition lastJobEndCondition, Verse.AI.ThinkNode jobGiver, System.Boolean resumeCurJobAfterwards, System.Boolean cancelBusyStances, Verse.ThinkTreeDef thinkTree, System.Nullable`1[T] tag, System.Boolean fromQueue, System.Boolean canReturnCurJobToPool) [0x002aa] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.AI.Pawn_JobTracker.TryFindAndStartJob () [0x000bd] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.AI.Pawn_JobTracker.EndCurrentJob (Verse.AI.JobCondition condition, System.Boolean startNewJob, System.Boolean canReturnToPool) [0x00161] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.Pawn_DraftController.set_Drafted (System.Boolean value) [0x0008d] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.Pawn_DraftController.<GetGizmos>b__13_1 () [0x00007] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.Command_Toggle.ProcessInput (UnityEngine.Event ev) [0x00007] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at Verse.GizmoGridDrawer.DrawGizmoGrid (System.Collections.Generic.IEnumerable`1[T] gizmos, System.Single startX, Verse.Gizmo& mouseoverGizmo) [0x0062a] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.InspectGizmoGrid.DrawInspectGizmoGridFor (System.Collections.Generic.IEnumerable`1[T] selectedObjects, Verse.Gizmo& mouseoverGizmo) [0x00209] in <c36f9493c9844ddaa7fb5c788416098f>:0 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
````

**_And the following two will alternate constantly:_**

````
JobDriver.GetReport() exception: System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.Pawn.GetInspectString () [0x002e0] in <c36f9493c9844ddaa7fb5c788416098f>:0 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
````

````
Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.ColonistBarColonistDrawer.DrawIcons (UnityEngine.Rect rect, Verse.Pawn colonist) [0x0014c] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.ColonistBarColonistDrawer.DrawColonist (UnityEngine.Rect rect, Verse.Pawn colonist, Verse.Map pawnMap, System.Boolean highlight, System.Boolean reordering) [0x001ad] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.ColonistBar.ColonistBarOnGUI () [0x00135] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.MapInterface.MapInterfaceOnGUI_BeforeMainTabs () [0x0003c] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at RimWorld.UIRoot_Play.UIRootOnGUI () [0x0001f] in <c36f9493c9844ddaa7fb5c788416098f>:0 
  at (wrapper dynamic-method) Verse.Root.Verse.Root.OnGUI_Patch1(Verse.Root)
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)
````

**Comment by Reiquard** [comment] 2021-02-07 13:14
While I was working on issue #131, I managed to draft a pawn (which was assigned for documentation) twice in a row, which also led to error spam - this has happened both with and without my changes there.

https://gist.github.com/34d4aefc3ef25775cf4908cac2f7081f

**Comment by jptrrs** [comment] 2021-02-07 13:22
Hi! Thanks for testing it without loading a save. After loading the same configuration you're using and repeating the steps you described, I managed to reproduce the same error, after a quick sucession of draft/undrafting. The weird thing is it just happened ONCE, and now every time I try again, the training job simply resumes without issues. I'm guessing it has something to do with the specific point in time when you draft or undraft the pawn. Or with the UI state. Are you getting the error every time? Or is it something that happens on occasion? You described:

>Redraft this pawn (it goes to the bow to start shooting the target stand);
Redraft it immediately again and here's an error popped up:

The error happens on drafting or on undrafting the pawn? And when does it happen, exactly? When the pawn is on his way to get the bow the first time, after he picked the bow and is on his way to the target stand or once he begins the training?
Also, since the UI seems to be affected, do you have the Tech tab open or closed when it happens?
Those are weird questions, I know, but that error seems to occur only in a freakishly specific situation!

**Comment by Reiquard** [comment] 2021-02-07 13:36
Just started and paused Lost Tribe scenario.

**_Abego is wandering._**
![screenshot1](https://user-images.githubusercontent.com/62316596/107147891-8475f800-6961-11eb-81c1-373f57fa8465.png)

**_Redrafted it - and its jobstring is "Training to use a ranged weapon." (while it's still in the same spot). The game still paused._**
![screenshot2](https://user-images.githubusercontent.com/62316596/107148498-783f6a00-6964-11eb-924a-711417914af1.png)

Redrafted it again while the game is still paused and Abego is in the same spot and got an error spam.

Errors start spamming when Abego exits the drafted state.
If we load this save, we will start getting errors on the fourth press of the **_R_** button while Abego is selected.

P.S.
If Abego has already directly started shooting, there will be no errors.
We also won't get any error if Abego has already taken the bow but has not directly started shooting.

**Comment by jptrrs** [comment] 2021-02-07 14:07
Got it. So, to wrap it up: the error only occurs if the game is paused while a pawn is moving to start the training job AND the player drafts and undrafts the pawn multiple times without unpausing. Is that right?
If that's the case, the probability of this happening in game is so low that I'm not sure its worth pursuing a solution.

**Comment by Reiquard** [comment] 2021-02-07 14:37
> So, to wrap it up: the error only occurs if the game is paused while a pawn is moving to start the training job AND the player drafts and undrafts the pawn multiple times without unpausing. Is that right?

That's _almost_ right. Not multiple times - **_once_** is enough.
The first drafting resets previous job and the pawn begins to move to the bow.
The second drafting (of be it a first, if the pawn was ordered manually or was it his own decision) leads to errors.

- The pawn started this job, but did not get to the weapon yet.
- If at this time the game is paused and the pawn is redrafted (once), we will get errors.

**But!**
If we redraft Abego without the game being paused and while he is moving to start his job, we won't get the error, but he will "lose interest" in this job;
he will wander around as if he doesn't have an assignment for this job.
And only right-clicking on the [Target Stand] (to get the menu, but without ordering) will reset its behavior.

Inserting
```
Log.Message($"If {Find.TickManager.TicksGame} >= {bill.lastIngredientSearchFailTicks} + {range.RandomInRange} || {FloatMenuMakerMap.makingFor == pawn}");
```
prior this [line](https://github.com/jptrrs/HumanResources/blob/baf4f2444aad8f7140bbaa522aa4e4a67b1b4887/Source/Work/WorkGiver_LearnWeapon.cs#L89) helped me to visualize internal logic of this behavior.

Speaking of not just this job, it also happens, at least when documenting (like I said earlier).

**Comment by jptrrs** [comment] 2021-02-08 15:26
>That's almost right. Not multiple times - once is enough.
The first drafting resets previous job and the pawn begins to move to the bow...

Well, if there's a first that goes well, that's because it requires multiple times :) I managed to reproduce the error only by striking the R key four times in a row, as you noticed yourself. 

Anyway, some useful information I found out about:  you can get out of the crashed state by using the "EndCurrentJob(InterruptForced)" option from the debug actions menu on the affected pawn.

**Comment by Reiquard** [comment] 2021-02-08 20:03
I wrote about four R presses for the simplicity of reproducing this situation.
You can skip the two first R presses by ordering the pawn to start training by right-clicking the target stand or catch the moment when the pawn starts training opportunistically and then pause the game.
Thus, it will only take one redraft (when the pawn is on its way to the weapon while the game is paused) to start getting the errors.

**Comment by jptrrs** [comment] 2021-02-09 16:00
I tested a number of things to figure out why this was happening with no success whatsoever. Gave up. Then, during a shower, the solution just occurred to me. As it turns out, that was a side-effect of the method I'm using to improve performance and keep sync between "HasJob" and "JobOnThing".  First time an update is corrected before even being launched. Thanks ;-)

**Closed as completed by jptrrs** 2021-02-09 16:00 UTC
Labels: bug
